apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse"
  namespace: click
spec:
  configuration:
    zookeeper:
      nodes:
        - host: "crs-zookeeper-0.zookeeper-headless.click.svc.cluster.local"
          port: 2181
        - host: "crs-zookeeper-1.zookeeper-headless.click.svc.cluster.local"
          port: 2181
        - host: "crs-zookeeper-2.zookeeper-headless.click.svc.cluster.local"
          port: 2181
    clusters:
      - name: "main"
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-pod-template
  defaults:
    templates:
      podTemplate: clickhouse-pod-template
      volumeClaimTemplate: clickhouse-storage-template
  templates:
    podTemplates:
      - name: clickhouse-pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:23.3
              resources:
                requests:
                  cpu: "1"
                  memory: "2Gi"
                limits:
                  cpu: "2"
                  memory: "4Gi"
              ports:
                - containerPort: 8123
                  name: http
                - containerPort: 9000
                  name: native
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
              readinessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 10
                periodSeconds: 10
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /ping
                  port: 8123
                initialDelaySeconds: 30
                periodSeconds: 30
                failureThreshold: 5
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi