apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-config
  namespace: kafka
data:
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ZOO_SERVERS: |
    crs-zookeeper-0.zookeeper-headless.kafka.svc.cluster.local:2888:3888
    crs-zookeeper-1.zookeeper-headless.kafka.svc.cluster.local:2888:3888
    crs-zookeeper-2.zookeeper-headless.kafka.svc.cluster.local:2888:3888
