apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper-cluster
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper-cluster
    