apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-zookeeper
  namespace: kafka
spec:
  serviceName: zookeeper-headless
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper-cluster
  template:
    metadata:
      labels:
        app: zookeeper-cluster
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          volumeMounts:
            - name: zookeeper-storage
              mountPath: /bitnami/zookeeper/data
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: ALLOW_ANONYMOUS_LOGIN
            - name: ZOO_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: zookeeper-config
                  key: ZOO_SERVERS
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    echo $(( $(hostname | awk -F '-' '{print $NF}') + 1 )) > /bitnami/zookeeper/data/myid
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi