apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
spec:
  clusterIP: None
  selector:
    app: kafka-cluster
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092