apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crs-kafka
  namespace: kafka
spec:
  replicas: 3
  serviceName: kafka-headless
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:2.6.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_ZOOKEEPER_CONNECT
        - name: KAFKA_CFG_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CFG_LISTENERS
        - name: ALLOW_PLAINTEXT_LISTENER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: ALLOW_PLAINTEXT_LISTENER
              
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://$(hostname).kafka-headless.kafka.svc.cluster.local:9092"
